### PR TITLE
add nightly with GurumDDS for Rolling

### PR DESCRIPTION
**Pull request by dirk-thomas**
> `jenkins_job_schedule: 15 23 * * 6`

Running only once a week on Saturdays.

See first builds of the job: http://build.ros2.org/view/Rci/job/Rci__nightly-gurumdds_ubuntu_focal_amd64/

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@nuclearsandwich Please feel free to close the PR if you think the compute resources shouldn't be spent on this.

(I have disabled the test job for now and will delete if the PR isn't being merged.)

**Comment by nuclearsandwich** [comment]
I'd prefer to conserve resources at the moment. We can re-open this PR in the future if we decide to commit them.

**Comment by dirk-thomas** [comment]
A brief list of failed tests for future readers:
* test_rmw_implementation.TestNodeConstructionDestruction__rmw_gurumdds_cpp.destroy_with_bad_arguments
* test_rmw_implementation.TestNodeConstructionDestruction__rmw_gurumdds_cpp.create_with_bad_arguments
* test_rmw_implementation.test_publisher__rmw_gurumdds_cpp.gtest.missing_result
* test_rclcpp.cppcheck.xunit.missing_result
* rosbag2_transport.test_record_all_no_discovery__rmw_gurumdds_cpp.gtest.missing_result
* rosbag2_transport.test_record_all__rmw_gurumdds_cpp.gtest.missing_result
* rosbag2_transport.test_record__rmw_gurumdds_cpp.gtest.missing_result
* ros2topic.ros2topic.test.test_echo_pub.test_echo_pub
* ros2topic.ros2topic.test.test_cli.test_cli
* ros2service.ros2service.test.test_cli.test_cli
* ros2param.ros2param.test.test_verb_dump.test_verb_dump
* ros2lifecycle.ros2lifecycle.test.test_cli.test_cli
* ros2action.ros2action.test.test_cli.test_cli
* rclpy.rclpy.test.test_init_shutdown.test_init_with_domain_id
* rclcpp.TestSerializedMessage.serialization
* rclcpp.TestAllocatorMemoryStrategy.number_of_entities_with_subscription
* rclcpp.test_executors.gtest.missing_result
* rcl.TestSubscriptionFixture__rmw_gurumdds_cpp.test_subscription_nominal
* rcl.TestServiceFixture__rmw_gurumdds_cpp.test_service_nominal
* rcl.TestNodeFixture__rmw_gurumdds_cpp.test_rcl_node_accessors
* rcl.TestGraphFixture__rmw_gurumdds_cpp.test_graph_query_functions
* rcl.NodeGraphMultiNodeFixture.test_node_info_subscriptions
* rcl.NodeGraphMultiNodeFixture.test_node_info_services
* rcl.NodeGraphMultiNodeFixture.test_node_info_publishers
* rcl.NodeGraphMultiNodeFixture.test_node_info_clients
* interactive_markers.TestInteractiveMarkerServerWithMarkers.update_communication

**Comment by nuclearsandwich** [comment]
I did not bother to review this initially because I was asked about the compute resources not the config. However, I'm not sure what was running in this job but rmw_gurumdds is not part of the repos file used in this config, nor was its dependency rosidl_typesupport_gurumdds (needed for gurumdds_cmake_module). Unless there's something I'm missing.

**Comment by dirk-thomas** [comment]
> I did not bother to review this initially because I was asked about the compute resources not the config. However, I'm not sure what was running in this job but rmw_gurumdds is not part of the repos file used in this config

Did you see these lines (https://github.com/ros2/ros_buildfarm_config/pull/117/files#diff-729bfd673b193aab0dacecc40f19d0c5R97)?

    repository_names:
    - rmw_gurumdds

> nor was its dependency rosidl_typesupport_gurumdds

Afaik they dropped the static typesupport in favor of using the dynamic / introspection typesupport.

Also the output of some of the failing tests showed a warning about a missing license for GurumDDS. So I am pretty confident the job was doing what it was expected to do.

**Pull request closed without merging**
