### PR TITLE
Unblock builds of Nav2 on RHEL 9

### PR DESCRIPTION
**Pull request by cottsay**
This reverts part of #285

xtensor was made available in RHEL 9 with ros/rosdistro#38843.

There are quite a few packages here, and I expect that some of them will need to reappear on this list for one reason or another, but the fastest and most reliable way to find out which ones fail to build is to try.

cc: @SteveMacenski

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
I'm OK with this, but we should wait for @SteveMacenski 's buy-in since he'll be the one getting the emails.

**Comment by SteveMacenski** [comment]
I've not heard any complaints from folks about RHEL not containing binaries of Nav2. However, its not that much overhead to check some emails and follow up here to blacklist the ones that cause problems, so I'm OK with it.

**Comment by cottsay** [comment]
Maintainer E-mails are still disabled for RHEL. You won't get anything new. I've been doing most of the package triage for RHEL myself.

https://github.com/ros2/ros_buildfarm_config/blob/d2607d7f81a04efd27417ab5f9e919aef30b129e/iron/release-rhel-build.yaml#L16

**Review by clalancette — APPROVED** [review]

**Comment by cottsay** [comment]
Following up here:

As a result of this change:
* 44 packages were unblocked and built successfully (33 listed here, 11 dependents of those listed here)
* 5 packages from this list automatically remained disabled due to listed upstream dependencies
  - Mostly OMPL, as @SteveMacenski already pointed out
* 1 package failed to build (0 listed here, 1 dependents of those listed here)
  - I'll note that the failure is `rtabmap_slam`, which also has a 50% failure rate on Jammy due to linking resource demands

So I take back what I said - nothing removed here need reappear. I'll call it a testament to the quality of navigation2 code and our approach to inter-platform packaging :)

**Comment by SteveMacenski** [comment]
What in nav2 depends on rtabmap?

**Comment by cottsay** [comment]
> What in nav2 depends on rtabmap?

My fault, I meant "downstream dependencies" or "dependents" of Nav2.

**Pull request merged**
