### PR TITLE
Add large messages and lost messages plots to nightly performance job, minor fixes in old plot labels

### PR DESCRIPTION
**Pull request by ivanpauno**
See https://github.com/ros2/buildfarm_perf_tests/pull/65.

### CODE REVIEW

**Review by cottsay — CHANGES_REQUESTED** [review]
I'm assuming that these changes are the result of running the script in `buildfarm_perf_tests`. It would be good to clarify that in the commit message.
I believe that changes to the `master` branch of `buildfarm_perf_tests` will be immediately deployed to Eloquent as well, so that config should be updated in this review as well.

**Comment by ivanpauno** [comment]
> I'm assuming that these changes are the result of running the script in buildfarm_perf_tests. It would be good to clarify that in the commit message.

Yes, that's the case.
I will update the commit message.

> I believe that changes to the master branch of buildfarm_perf_tests will be immediately deployed to Eloquent as well, so that config should be updated in this review as well.

Sounds good.

**Review by ahcorde — CHANGES_REQUESTED** [review]
Changes LGTM, just add the Eloquent plots too

**Comment by ivanpauno** [comment]
Some of the modifications are leftovers from https://github.com/ros2/ros_buildfarm_config/pull/102.

**Review by cottsay — APPROVED** [review]
LGTM, as long as https://github.com/ros2/buildfarm_perf_tests/pull/65/commits/b0e1df250b0c8b59e4dfdb8d8d1f3ec7a459f957 was included.

**Comment by ivanpauno** [comment]
> LGTM, as long as [ros2/buildfarm_perf_tests@b0e1df2](https://github.com/ros2/buildfarm_perf_tests/commit/b0e1df250b0c8b59e4dfdb8d8d1f3ec7a459f957) was included.

Yeap, it was.

**Pull request merged**
