### PR TITLE
Add in Humble CI.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

These adds in the CI jobs for Humble.  I took the CI jobs from Rolling, copied them into the `humble` subdirectory, and then changed the ros2.repos URL to https://github.com/ros2/ros2/raw/humble/ros2.repos everywhere.

Somewhat controversially, I also removed any jobs that were specifically dealing with fastrtps-dynamic.  It's status is sort of in limbo, and it allowed us to cut down on the number of additional CI jobs we are adding here.  If we really feel like we want it, I can add it back in.

### CODE REVIEW

**Review by audrow — APPROVED** [review]
Looks good to me, and I think removing fastrtps-dynamic sounds okay.

**Review by cottsay — CHANGES_REQUESTED** [review]
> I also removed any jobs that were specifically dealing with fastrtps-dynamic.

Pretty sure we had this conversation when we added CI for Galactic, and I'm pretty sure we had a decent reason to keep it then. Something about static vs dynamic typesupport. I'm not going to die on this hill and it's not my call anyway, but I think we should come up with better justification to remove it. Seems like a solution looking for a problem.

---

The `jenkins_job_schedule` entries should be updated. We build Rolling nightly, but we only build released distros every 3 days. Foxy is `15 23 1-31/3 * *`, Galactic is `15 23 3-30/3 * *`, so I believe that Humble should be `15 23 2-29/3 * *`.

The `jenkins_job_priority` also needs to be revised. Foxy is `57`, Galactic is `56`, and Rolling is `50`, so I think it makes sense for Humble to build at `55`.

**Comment by clalancette** [comment]
> Seems like a solution looking for a problem.

The problem is the sheer number of CI jobs we have; *before* this PR, if I count across https://ci.ros2.org and https://build.ros2.org, we have 72 CI jobs.  With this PR in its current state, we are adding another 11 jobs, and adding in the fastrtps-dynamic ones adds 4 more.  It's just far too many for a small team to deal with (and you can see this by the fact that a large number of them are failing for one reason or another).

That said, I kind of wanted to cause this discussion, so I'm also willing to put them back.  I'm interested to hear what the rest of @ros2/team has to say about it.

I definitely have to fix the rest of your comments (thanks for the review), so I'll go ahead and do that for now.

**Comment by clalancette** [comment]
One thing I noticed while changing the job schedule is that some CI jobs don't have a `jenkins_job_schedule` (either in Galactic or Humble).  For instance, https://github.com/ros2/ros_buildfarm_config/blob/349d9c4ae6380fb197ab1245b993665111382086/galactic/ci-nightly-fastrtps.yaml#L24 has one, but https://github.com/ros2/ros_buildfarm_config/blob/349d9c4ae6380fb197ab1245b993665111382086/galactic/ci-nightly-cross-vendor-connext-cyclonedds.yaml does not.  Any thoughts on why that is?

**Comment by cottsay** [comment]
> some CI jobs don't have a `jenkins_job_schedule`

The jobs without a schedule are triggered when their upstream nightly job finishes. The config for that is `jenkins_job_upstream_triggers`.

**Comment by clalancette** [comment]
> The jobs without a schedule are triggered when their upstream nightly job finishes. The config for that is `jenkins_job_upstream_triggers`.

Ah, makes sense, thanks.

**Comment by clalancette** [comment]
> That said, I kind of wanted to cause this discussion, so I'm also willing to put them back. I'm interested to hear what the rest of @ros2/team has to say about it.

After discussing it with the team, we decided to keep the fastrtps-dynamic jobs for now.  So I'll add those back in.

**Comment by clalancette** [comment]
> > 
> 
> After discussing it with the team, we decided to keep the fastrtps-dynamic jobs for now. So I'll add those back in.

And this is done now in 6800b2d

**Review by ivanpauno — APPROVED** [review]
lgtm!

**Comment by wjwwood** [comment]
> With this PR in its current state, we are adding another 11 jobs, and adding in the fastrtps-dynamic ones adds 4 more. It's just far too many for a small team to deal with (and you can see this by the fact that a large number of them are failing for one reason or another).

While that's true, avoiding these 4 jobs doesn't meaningfully address the issue in my opinion. So I don't think it's a good reason to avoid them. We should instead remove many more of the jobs (based on some rationale), e.g. remove all fastrtps-dynamic jobs on all releases because we don't value them (a different discussion), improve the tools to make them easier to manage, or increase the resources we spend on it, or something else I haven't thought of. Those things would actual solve the problem, avoiding these four jobs don't, again in my opinion.

I wouldn't remove them with this rationale.

**Comment by clalancette** [comment]
> I wouldn't remove them with this rationale.

I've added them back in now.  We still have the larger issue, but this isn't the place to solve it.

**Comment by clalancette** [comment]
Given the approval here, I'm going to go ahead and merge this.  If there are follow-up items, please let me know and I'll open a separate PR to address them.

**Pull request merged**
