### PR TITLE
Blacklist ros_workspace dev job

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Since this is the which package provides environment scripts there are none for it to source during a dev job in order to find the ament_cmake_core package so its dev job will always fail with

```
04:15:20 CMake Error at CMakeLists.txt:4 (find_package):
04:15:20   By not providing "Findament_cmake_core.cmake" in CMAKE_MODULE_PATH this
04:15:20   project has asked CMake to find a package configuration file provided by
04:15:20   "ament_cmake_core", but CMake did not find one.
04:15:20 
04:15:20   Could not find a package configuration file provided by "ament_cmake_core"
04:15:20   with any of the following names:
04:15:20 
04:15:20     ament_cmake_coreConfig.cmake
04:15:20     ament_cmake_core-config.cmake
04:15:20 
04:15:20   Add the installation prefix of "ament_cmake_core" to CMAKE_PREFIX_PATH or
04:15:20   set "ament_cmake_core_DIR" to a directory containing one of the above
04:15:20   files.  If "ament_cmake_core" provides a separate development package or
04:15:20   SDK, be sure it has been installed.
04:15:20 
04:15:20 
04:15:20 -- Configuring incomplete, errors occurred!
04:15:20 See also "/tmp/catkin_workspace/build/ros_workspace/CMakeFiles/CMakeOutput.log".
04:15:20 --- stderr: ros_workspace
```

For debian builds the debian/rules file for this package sets up the CMAKE_PREFIX_PATH but I'm not aware of any environment configuration for dev jobs that would let us do the same.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
unfortunately it is a bit larger scope than this as these failures will happen for any package that depends only on `ament_package` or `ament_cmake_core`.

I'm not opposed to merge this as is, but am trying to think of a more generic approach for dev jobs

**Comment by nuclearsandwich** [comment]
> unfortunately it is a bit larger scope than this as these failures will happen for any package that depends only on ament_package or ament_cmake_core.

The situation for the ros_workspace package is a bit different. The dev jobs for packages above ros_workspace could be fixed by installing ros_workspace (or whatever package provides the environment scripts in the future) but since the environment scripts are provided by ros_workspace unless we let the previous version of the package provide for the dev job we don't have anything to do that job.

**Comment by mikaelarguedas** [comment]
> The situation for the ros_workspace package is a bit different. The dev jobs for packages above ros_workspace could be fixed by installing ros_workspace

:+1:
the other repos that we know are below (ament_cmake and ament_package) will face the same issue though

> since the environment scripts are provided by ros_workspace unless we let the previous version of the package provide for the dev job we don't have anything to do that job.

agreed

**Review by dirk-thomas — CHANGES_REQUESTED** [review]
Since we don't want devel jobs for `ros_workspace` in the first place they shouldn't be disabled in the config but also be disabled in the distribution file.

**Comment by mikaelarguedas** [comment]
> Since we don't want devel jobs for ros_workspace in the first place they shouldn't be disabled in the config but also be disabled in the distribution file.

:+1: I asked the question on https://github.com/ros2/rosdistro/pull/86#issuecomment-397185885, and was waiting for feedback to open a follow-up

**Comment by nuclearsandwich** [comment]
Proposed https://github.com/ros2/rosdistro/pull/88 instead.

**Pull request closed without merging**
