### PR TITLE
Add CI jobs for ROS 2 Galactic

### PR DESCRIPTION
**Pull request by cottsay**
Follow-up to #155

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
I have two meta-comments here:

1. I think we should just drop any CI jobs that deal with fastrtps-dynamic.  We really don't do much testing on it, and I'd like to actually drop the CI jobs for it in past releases.
2. I'm concerned about the number of jobs being added.  The above point will help, but given the large number of jobs that are already being run on build.ros2.org, I'm not sure that all of the jobs will complete within 24 hours.  I'm not entirely sure what to do about that, but I just thought I'd raise the concern.

**Comment by cottsay** [comment]
I updated these jobs to fit into the every-third-day schedule we're using for Foxy and Dashing. This means that these jobs won't cause the overall CI job load to increase, and will just fill the daily slot that Eloquent had. This is how it should have been from the start, it was an oversight on my part that it was omitted.

From a quick survey of Foxy and Rolling jobs, it looks like they're completing nightlies in under 8 hours per distro. Running all 4 distros would take around 30 hours, but since we run 3 of them only every third night, each night should be done in under 16 hours, so we have quite a bit of wiggle room before we're pushing on 24 hours.

The fastrtps-dynamic jobs add a total of 3:20 hrs of compute time out of a total 29:45 hrs of compute for a full nightly run for a distro (roughly 11% of the resources). Of course it isn't this simple, but roughly speaking, 11% of 8 hours is about 53 minutes. So dropping fastrtps-dynamic from each distro would result in the CI workers going idle around 1:45 hrs sooner each day. Given that this is pretty much the only place where we exercise fastrtps-dynamic regularly, I think it's worth keeping the jobs.

**Comment by clalancette** [comment]
> The fastrtps-dynamic jobs add a total of 3:20 hrs of compute time out of a total 29:45 hrs of compute for a full nightly run for a distro (roughly 11% of the resources). Of course it isn't this simple, but roughly speaking, 11% of 8 hours is about 53 minutes. So dropping fastrtps-dynamic from each distro would result in the CI workers going idle around 1:45 hrs sooner each day. Given that this is pretty much the only place where we exercise fastrtps-dynamic regularly, I think it's worth keeping the jobs.

So the thing I'm worried here isn't really the CI worker time (that concern seems to be mitigated by only running every 3rd night).  It's the overall maintenance load for the ROS 2 team with the fastrtps-dynamic jobs.  Those jobs are so low on the priority list that they may as well be non-existent; we'll essentially never get to fixing and triaging issues in them.  So I'm not sure it is worth running them at all, since we never test or look at them in any other context.

(separately, I'd like to look at actually removing the fastrtps-dynamic code from the codebase, but that is somewhat orthogonal to this)

**Comment by nuclearsandwich** [comment]
> It's the overall maintenance load for the ROS 2 team with the fastrtps-dynamic jobs. Those jobs are so low on the priority list that they may as well be non-existent; we'll essentially never get to fixing and triaging issues in them. So I'm not sure it is worth running them at all, since we never test or look at them in any other context.
> 
> (separately, I'd like to look at actually removing the fastrtps-dynamic code from the codebase, but that is somewhat orthogonal to this)

I definitely get what you're saying here. There's a cognitive load required to actively know which jobs are priority and which can be "mostly ignored" but since rmw_fastrtps_dynamic_cpp is listed at Tier 2 in all currently active ROS distributions (and Galactic, which is in prerelease) [source: REP-2000](https://github.com/ros-infrastructure/rep/blob/master/rep-2000.rst). I don't think we can retire the jobs anywhere but for Rolling and I would recommend doing so in tandem with deprecating and removing the package source so that we're not in a position where it looks like it should be working but isn't.

**Review by nuclearsandwich — APPROVED** [review]
I did not do a close reading of the job configurations themselves since I expect that they're copied from rolling but I did check for missed copypaste fallout like references to rolling and foxy and found none.

**Pull request merged**
