### PR TITLE
Give Foxy jobs higher priority over Eloquent jobs

### PR DESCRIPTION
**Pull request by jacobperron**
Addresses https://github.com/ros2/ros_buildfarm_config/pull/50/files#r376016874

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Comment by cottsay** [comment]
FYI: As described in #49, we're starting to collide between priority levels under this scheme.

**Comment by dirk-thomas** [comment]
> As described in #49, we're starting to collide between priority levels under this scheme.

Not yet for this specific change.

**Comment by cottsay** [comment]
> Not yet for this specific change.

Looks like the Crystal jobs are gone, so I need to update that issue.

**Comment by dirk-thomas** [comment]
@jacobperron Was this change deployed to Jenkins?

**Comment by jacobperron** [comment]
I didn't manually trigger any deployment; I figured this would happen as part of Fci_reconfigure, but looks like it's been failing:

http://build.ros2.org/job/Fci_reconfigure-jobs/17

Looking into it :eyes:

**Comment by jacobperron** [comment]
The job was failing because of a warning being printed [from here](https://github.com/ros-infrastructure/ros_buildfarm/blob/5b5e2b16438384b913c144daf9cbbf533bbd3389/ros_buildfarm/git.py#L49). The last time ran the generate_all_joys.py script, I had cloned the repo as

`git@github.com:ros-infrastructure/ros_buildfarm`

instead of

 `git@github.com:ros-infrastructure/ros_buildfarm.git`

**Comment by jacobperron** [comment]
I don't have a clue for the latest failure: http://build.ros2.org/job/Fci_reconfigure-jobs/18/

**Comment by dirk-thomas** [comment]
> I don't have a clue for the latest failure: http://build.ros2.org/job/Fci_reconfigure-jobs/18/

`docker` just died. I retriggered the job and the latest build passed: http://build.ros2.org/job/Fci_reconfigure-jobs/19/

@nuclearsandwich has looked into these sporadic docker failures but afaik hasn't found the source of the problem yet.

**Pull request merged**
