### PR TITLE
[foxy] Get ROS 1 packages from the testing repository

### PR DESCRIPTION
**Pull request by jacobperron**
This resolves an issue finding Noetic packages that are not yet available in the main repository.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The cross-vendor jobs shouldn't need the ROS 1 repo, no?

**Comment by jacobperron** [comment]
I don't think so, it was just pointing to the repository so I changed it anyways. I can remove it altogether if you think it's appropriate.

**Review by dirk-thomas — APPROVED** [review]

**Comment by dirk-thomas** [comment]
@jacobperron For the cross-vendor build files the obsolete repository ~URL~ keys must be be removed too: http://build.ros2.org/job/Fci_reconfigure-jobs/64/console#console-section-5

**Comment by jacobperron** [comment]
@dirk-thomas Do you mean the obsolete repository GPG key? I think that's what the job is complaining about.

**Comment by jacobperron** [comment]
See https://github.com/ros2/ros_buildfarm_config/pull/85

**Pull request merged**
