### PR TITLE
Add job weight of 4 to CI jobs.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
This is needed to enable unified our build agents for CI
jobs (https://github.com/ros2/ros_buildfarm_config/issues/141)

Once this is deployed I'm pretty sure the heavy job behavior will prevent jobs from being queued on the single-executor ci-agents. My solution for that is to bump those up to four executors while we figure out the priority settling.

### CODE REVIEW

**Review by cottsay — APPROVED** [review]
👍

**Comment by nuclearsandwich** [comment]
Job priorities now that everything lives in the same pool.

```
40
  jenkins_pull_request_job_priority::rolling/source-build.yaml
47
  jenkins_pull_request_job_priority::foxy/source-build.yaml
48
  jenkins_pull_request_job_priority::eloquent/source-build.yaml
49
  jenkins_pull_request_job_priority::dashing/source-build.yaml
50
  jenkins_commit_job_priority::rolling/source-build.yaml
  jenkins_job_priority::rolling/ci-benchmark.yaml
  jenkins_job_priority::rolling/ci-nightly-connext.yaml
  jenkins_job_priority::rolling/ci-nightly-cross-vendor-connext-cyclonedds.yaml
  jenkins_job_priority::rolling/ci-nightly-cross-vendor-connext-fastrtps-dynamic.yaml
  jenkins_job_priority::rolling/ci-nightly-cross-vendor-connext-fastrtps.yaml
  jenkins_job_priority::rolling/ci-nightly-cross-vendor-cyclonedds-fastrtps-dynamic.yaml
  jenkins_job_priority::rolling/ci-nightly-cross-vendor-cyclonedds-fastrtps.yaml
  jenkins_job_priority::rolling/ci-nightly-cross-vendor-fastrtps-fastrtps-dynamic.yaml
  jenkins_job_priority::rolling/ci-nightly-cyclonedds.yaml
  jenkins_job_priority::rolling/ci-nightly-debug.yaml
  jenkins_job_priority::rolling/ci-nightly-extra-rmw-release.yaml
  jenkins_job_priority::rolling/ci-nightly-fastrtps-dynamic.yaml
  jenkins_job_priority::rolling/ci-nightly-fastrtps.yaml
  jenkins_job_priority::rolling/ci-nightly-performance.yaml
  jenkins_job_priority::rolling/ci-nightly-release.yaml
  jenkins_job_priority::rolling/ci-overlay.yaml
57
  jenkins_commit_job_priority::foxy/source-build.yaml
  jenkins_job_priority::foxy/ci-benchmark.yaml
  jenkins_job_priority::foxy/ci-nightly-connext.yaml
  jenkins_job_priority::foxy/ci-nightly-cross-vendor-connext-cyclonedds.yaml
  jenkins_job_priority::foxy/ci-nightly-cross-vendor-connext-fastrtps-dynamic.yaml
  jenkins_job_priority::foxy/ci-nightly-cross-vendor-connext-fastrtps.yaml
  jenkins_job_priority::foxy/ci-nightly-cross-vendor-cyclonedds-fastrtps-dynamic.yaml
  jenkins_job_priority::foxy/ci-nightly-cross-vendor-cyclonedds-fastrtps.yaml
  jenkins_job_priority::foxy/ci-nightly-cross-vendor-fastrtps-fastrtps-dynamic.yaml
  jenkins_job_priority::foxy/ci-nightly-cyclonedds.yaml
  jenkins_job_priority::foxy/ci-nightly-debug.yaml
  jenkins_job_priority::foxy/ci-nightly-extra-rmw-release.yaml
  jenkins_job_priority::foxy/ci-nightly-fastrtps-dynamic.yaml
  jenkins_job_priority::foxy/ci-nightly-fastrtps.yaml
  jenkins_job_priority::foxy/ci-nightly-performance.yaml
  jenkins_job_priority::foxy/ci-nightly-release.yaml
  jenkins_job_priority::foxy/ci-overlay.yaml
58
  jenkins_commit_job_priority::eloquent/source-build.yaml
  jenkins_job_priority::eloquent/ci-nightly-connext.yaml
  jenkins_job_priority::eloquent/ci-nightly-cyclonedds.yaml
  jenkins_job_priority::eloquent/ci-nightly-debug.yaml
  jenkins_job_priority::eloquent/ci-nightly-extra-rmw-release.yaml
  jenkins_job_priority::eloquent/ci-nightly-fastrtps-dynamic.yaml
  jenkins_job_priority::eloquent/ci-nightly-fastrtps.yaml
  jenkins_job_priority::eloquent/ci-nightly-opensplice.yaml
  jenkins_job_priority::eloquent/ci-nightly-performance.yaml
  jenkins_job_priority::eloquent/ci-nightly-release.yaml
  jenkins_job_priority::eloquent/ci-overlay.yaml
59
  jenkins_commit_job_priority::dashing/source-build.yaml
  jenkins_job_priority::dashing/ci-nightly-connext.yaml
  jenkins_job_priority::dashing/ci-nightly-cyclonedds.yaml
  jenkins_job_priority::dashing/ci-nightly-debug.yaml
  jenkins_job_priority::dashing/ci-nightly-extra-rmw-release.yaml
  jenkins_job_priority::dashing/ci-nightly-fastrtps-dynamic.yaml
  jenkins_job_priority::dashing/ci-nightly-fastrtps.yaml
  jenkins_job_priority::dashing/ci-nightly-opensplice.yaml
  jenkins_job_priority::dashing/ci-nightly-performance.yaml
  jenkins_job_priority::dashing/ci-nightly-release.yaml
  jenkins_job_priority::dashing/ci-overlay.yaml
70
  jenkins_source_job_priority::rolling/release-build.yaml
  jenkins_source_job_priority::rolling/release-focal-arm64-build.yaml
77
  jenkins_source_job_priority::foxy/release-build.yaml
  jenkins_source_job_priority::foxy/release-focal-arm64-build.yaml
  jenkins_source_job_priority::foxy/release-focal-armhf-build.yaml
78
  jenkins_source_job_priority::eloquent/release-bionic-arm64-build.yaml
  jenkins_source_job_priority::eloquent/release-bionic-armhf-build.yaml
  jenkins_source_job_priority::eloquent/release-build.yaml
79
  jenkins_source_job_priority::dashing/release-bionic-arm64-build.yaml
  jenkins_source_job_priority::dashing/release-bionic-armhf-build.yaml
  jenkins_source_job_priority::dashing/release-build.yaml
80
  jenkins_binary_job_priority::rolling/release-build.yaml
  jenkins_binary_job_priority::rolling/release-focal-arm64-build.yaml
87
  jenkins_binary_job_priority::foxy/release-build.yaml
  jenkins_binary_job_priority::foxy/release-focal-arm64-build.yaml
88
  jenkins_binary_job_priority::eloquent/release-bionic-arm64-build.yaml
  jenkins_binary_job_priority::eloquent/release-build.yaml
89
  jenkins_binary_job_priority::dashing/release-bionic-arm64-build.yaml
  jenkins_binary_job_priority::dashing/release-build.yaml
97
  jenkins_binary_job_priority::foxy/release-focal-armhf-build.yaml
98
  jenkins_binary_job_priority::eloquent/release-bionic-armhf-build.yaml
99
  jenkins_binary_job_priority::dashing/release-bionic-armhf-build.yaml
```

**Comment by cottsay** [comment]
Keep in mind that the labels will keep the allocation as-is unless the jobs or workers are changed in that respect as well. Regardless, this is a step forward.

**Comment by nuclearsandwich** [comment]
> Keep in mind that the labels will keep the allocation as-is unless the jobs or workers are changed in that respect as well. Regardless, this is a step forward.

Yeah I suppose it would make sense to put a full plan forward some where. Lemme do dat.

**Comment by nuclearsandwich** [comment]
Reconfigure jobs deploying this change:
* http://build.ros2.org/job/Dci_reconfigure-jobs/605/
* http://build.ros2.org/job/Eci_reconfigure-jobs/520/
* http://build.ros2.org/job/Fci_reconfigure-jobs/308/
* http://build.ros2.org/job/Rci_reconfigure-jobs/137/

**Pull request merged**
