### PR TITLE
Add ouster_msgs to excluded packages on Rolling and Humble.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
This is a followup to #236 and #237.
Although this package does not directly or indirectly depend on
libtins-dev, when bloom fails to resolve rosdep keys for the sibling
package ros2_ouster it drops all release metadata for the platform in
that repository regardless of individual package.

As a result the sourcepkg job for RHEL fails since the expected tags are
missing in the bloom repository.

It is possible that a future enhancement to bloom could process sibling
packages individually and allow ouster_msgs to continue building in this
situation but for now the only way to get ouster_msgs building on RHEL
would be to split it out into its own repository.

Humble sourcepkg job: https://build.ros2.org/job/Hsrc_el8__ouster_msgs__rhel_8__source/
Rolling sourcepkg job: https://build.ros2.org/job/Rsrc_el8__ouster_msgs__rhel_8__source/

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
FYI @SteveMacenski.

Edit: more words.

First off, I'm grateful that you were proactive about updating the buildfarm configurations for situations you knew wouldn't be successful. It cuts down on our email traffic as well as your own. It's worth noting that this is an unusual case, although probably not very extraordinary and I certainly wouldn't have caught it during a review although now it's something I'll keep an eye out for. I think that more often than not there are inter-dependencies between the sibling packages which block cause them to block each other when one is blacklisted.

**Comment by SteveMacenski** [comment]
OK - thanks for letting me know, I'll keep that in mind in the future

**Comment by cottsay** [comment]
I recommend replacing the `ros2_ouster` entry with this one, which is upstream of `ros2_ouster`. It helps to keep this list small and maintainable.

**Comment by nuclearsandwich** [comment]
> I recommend replacing the `ros2_ouster` entry with this one, which is upstream of `ros2_ouster`. It helps to keep this list small and maintainable.

Ah I thought I'd checked and didn't see a direct dependency beteween them but [there it is](https://github.com/ros-drivers/ros2_ouster_drivers/blob/fb7402851b313ec5e03c13934ce59d4db06ef009/ros2_ouster/package.xml#L20).
I agree and I'll update the PR.

**Comment by cottsay** [comment]
Closed via #250

**Pull request closed without merging**
