### PR TITLE
Remove foxy navigation2 jobs

### PR DESCRIPTION
**Pull request by mjcarroll**
As discussed with @ruffsl and @SteveMacenski, these jobs are no longer necessary for `foxy`/`master`, since navigation2 is using CircleCI.

Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Comment by dirk-thomas** [comment]
@mjcarroll Please also remove the obsolete jobs from Jenkins.

**Comment by cottsay** [comment]
@mjcarroll - are the Eloquent jobs providing any value? Should they be removed as well?

**Comment by cottsay** [comment]
> @mjcarroll Please also remove the obsolete jobs from Jenkins.

We're going to keep seeing reconfigure job failures until this is deployed: http://build.ros2.org/job/Fci_reconfigure-jobs/62

**Comment by mjcarroll** [comment]
> @mjcarroll - are the Eloquent jobs providing any value? Should they be removed as well?

Good point, they can be removed because I haven't heard otherwise: https://github.com/ros2/ros_buildfarm_config/pull/83

**Comment by mjcarroll** [comment]
> We're going to keep seeing reconfigure job failures until this is deployed: http://build.ros2.org/job/Fci_reconfigure-jobs/62

I will redeploy once #83 is in.

**Pull request merged**
