### PR TITLE
Set build tool per distro

### PR DESCRIPTION
**Pull request by dirk-thomas**
This is in preparation of ros-infrastructure/ros_buildfarm#585.

The `ros_version` is necessary to decide about the installation of the `catkin` or `ros-workspace` package without the need to hardcode ROS distro names in the `ros_buildfarm` code.

The `build_tool` option is used to choose `colcon` over the default (which is `catkin_make_isolated`). The option is independent from the ROS version since it should be possible to build ROS 1 distributions with `colcon`.

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]

**Comment by dirk-thomas** [comment]
Regarding the `ros_version` I think the information should actually go into the rosdistro repository (since it is not a buildfarm specific annotation). Therefore I opened ros-infrastructure/rep#181 and ros-infrastructure/rosdistro#124 as well as reverted the first commit in this PR.

The build tool on the other hand is a buildfarm specific annotation and should stay here as is.

**Comment by nuclearsandwich** [comment]
@dirk-thomas what jobs are affected by the setting of `build_tool` for the `release-build` files?

**Comment by dirk-thomas** [comment]
> what jobs are affected by the setting of `build_tool` for the `release-build` files?

Oh, none. The `build_tool` option is only supposed to be set for `doc` (none atm) and `source` build files (only Bouncy). Fixed in c097e0d2ba259c4bc2e612382186b9094ec9b0aa.

**Review by nuclearsandwich — APPROVED** [review]
I haven't yet tested deploying this but it looks cromulent with the ros_buildfarm and rosdistro updates under discussion.

**Comment by dirk-thomas** [comment]
I have updated the patch to point to the new v4 index from ros2/rosdistro#282.

**Comment by dirk-thomas** [comment]
@jacobperron @nuclearsandwich Please take another look since this has changed quite a bit since then. Thanks.

**Comment by dirk-thomas** [comment]
I will go ahead and merge this to move forward on the remaining PRs. Please feel free to comment after the fact and I am happy to address comments.

**Pull request merged**
